import type {Metadata} from "next";

import Link from "next/link";

import {Toaster} from "@/components/ui/toaster";
import "./globals.css";

export const metadata: Metadata = {
  title: "colirank",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="relative h-screen w-screen overflow-hidden bg-slate-950">
        <div className="absolute top-0 z-[-2] h-screen w-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_35%_-5%,rgba(120,119,198,0.3),rgba(255,255,255,0))]" />
        <div className="container relative z-10 m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4 font-sans antialiased">
          <header className="text-2xl font-bold leading-[4rem] text-white">
            <Link href="/">colirank</Link>
          </header>
          <main className="py-8">{children}</main>
          <Toaster />
          <footer className="text-center leading-[4rem] text-white opacity-70">
            © {new Date().getFullYear()} colirank
          </footer>
        </div>
      </body>
    </html>
  );
}
